### ISSUE TITLE
Applying a patch gets a bit wonky

### ISSUE THREAD

**Issue by mapk** [folletto/WPdo#11]
I was trying to apply a patch today and came across these issues:

From the root directory in terminal, I typed `wpdo patch https://core.trac.wordpress.org/attachment/ticket/40702/40702.diff` and got this:

![screen shot 2017-05-09 at 1 54 55 pm](https://cloud.githubusercontent.com/assets/617986/25872331/22387fbc-34bf-11e7-87eb-6ae4fecce69d.png)

It also created a `src` directory which I had to delete afterwards. 

Is this an issue with how `wpdo patch` works, or with the patch itself?

**Comment by folletto** [comment]
When I ran manually the patch command (`patch -p0 < _wpdo_downloaded.patch`) it referred to:

```
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git src/wp-admin/css/dashboard.css src/wp-admin/css/dashboard.css
|index 98fb99378d..2b80450a4a 100644
|--- src/wp-admin/css/dashboard.css
|+++ src/wp-admin/css/dashboard.css
--------------------------
File to patch:
```

It looks like the patch was created from the wrong path (up one folder, from a user that has `src` as a sub-folder).

I tested other patches, and they are instead:

```
--- wp-includes/taxonomy.php	(revision 39927)
+++ wp-includes/taxonomy.php	(working copy)
```

Without `src/`. It might be people that are creating patches from the `git` codebase. I'm not 100% sure.

**Comment by folletto** [comment]
Thanks to _iandunn_ I've a way forward to try:

1. Try to detect if the patch URL isn't at the right WP root level
2. Change the `-p0` parameter accordingly.

**Comment by folletto** [comment]
This was a bit difficult to track down because `trunk` was moving, and the patches thus became obsolete.

However, I was able to do still a set of improvements that should improve various aspects:

1. Detection of `src/` path (the patch was likely made from `develop` (i.e. `develop.git.wordpress.org`) instead of `core` (i.e. `core.git.wordpress.org`). If present instead of `patch -p0` does `patch -p1`.
2. Improved detection of patch numbers: now `wpdo patch 00000`, `wpdo patch 00000.2`, `wpdo patch https://core.trac.wordpress.org/ticket/00000`, `wpdo patch https://core.trac.wordpress.org/attachment/ticket/00000/00000.2.diff` all work.
3. Mention of all the files that were changes after patching using `svn status`.
4. Display of the `patch` command to run in case of error.
